version: '3'

services:
  appointments:
    image: abd444168/appointments:b64c5b6
    ports:
      - "7070:7070"
    environment:
      - DATABASE_URL=mysql://db:3306/
    networks:
      - project-network

  doctors:
    image: abd444168/doctors:928d5a2
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URL=mysql://db:3306/
    networks:
      - project-network

  frontend:
    image: abd444168/frontend:bc99cfa
    ports:
      - "3000:3000"
    depends_on:
      - doctors
      - appointments
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - project-network

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=dummy-database
    networks:
      - project-network

networks:
  project-network: