apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors
        image: abd444168/doctors:latest
        ports:
        - containerPort: 9090
        env:
        - name: DATABASE_URL
          value: "mysql://db:3306/"

---

apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
  - port: 9090
    targetPort: 9090
