name: Build and Push Appointments Service

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'appointments/**'
  push:
    branches: [ main ]
    paths:
      - 'appointments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT }}
          
    - name: Get Short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA::7})"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./appointments
        file: ./appointments/Dockerfile
        push: true
        tags: abd444168/appointments:${{ steps.slug.outputs.sha7 }}
        
    - name: Update script perms
      run: chmod +x update-compose-version.sh
      
    - name: Update docker-compose file
      run: ./update-compose-version.sh appointments ${{ steps.slug.outputs.sha7 }}
    
    - name: Commit and Push docker-compose.yml
      run: |
        git config --global user.name 'Abdullah-Ranjha'
        git add docker-compose.yml
        git commit -m "Update appointments image to ${{ steps.slug.outputs.sha7 }}"
        git push
